import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Shield, Users, Activity, Search, LogOut } from "lucide-react";

type AdminUser = { id: string; name: string; email: string; role: "user" | "admin" | "super_admin"; status: "active" | "expired" | "suspended" | "deactivated"; plan: string; planLabel?: string; subscriptionStatus?: string; subscriptionType?: string; trialEndsAt?: string; subscriptionEndsAt?: string; daysRemaining?: number | null; lastPaymentAt?: string; paymentProvider?: string; planOverride?: string; mustChangePassword?: boolean; createdAt?: string; lastActiveAt?: string; usage?: Record<string, number> };
type Overview = { totalUsers: number; activeUsers: number; suspendedUsers: number; totalSessions: number; totalCaptionMinutes: number; totalTranslationMinutes: number; totalDubbingJobs: number; newUsersToday: number; newUsersThisMonth: number; plans: Record<string, number>; subscription?: { trialUsers: number; premiumUsers: number; expiredUsers: number; unlimitedUsers: number; monthlyRevenue: number }; recentActivity: Array<{ id: string; name: string; lastActiveAt?: string }> };
type Audit = { _id: string; action: string; reason?: string; createdAt: string; targetUserId?: string };

class AdminRequestError extends Error {
  status: number;

  constructor(message: string, status: number) {
    super(message);
    this.name = "AdminRequestError";
    this.status = status;
  }
}

const jsonRequest = async <T,>(api: string, path: string, token: string, options: RequestInit = {}): Promise<T> => {
  const response = await fetch(`${api}${path}`, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...options.headers } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new AdminRequestError(body.error || "Admin request failed.", response.status);
  return body;
};

const subscriptionEndLabel = (user: AdminUser) => {
  const unlimited = user.role === "admin" || user.role === "super_admin" || user.subscriptionType === "unlimited";
  if (unlimited) return "Never expires";
  if (user.status === "expired" || user.subscriptionStatus === "expired") return "Expired";
  if (user.subscriptionEndsAt) return new Date(user.subscriptionEndsAt).toLocaleDateString();
  if (user.subscriptionType === "trial") return "Trial only";
  return "Not active";
};

export function AdminLogin({ api, error, busy, onLogin }: { api: string; error: string | null; busy: boolean; onLogin: (email: string, password: string) => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  return <main className="mx-auto flex min-h-[calc(100dvh-76px)] w-full max-w-md items-center px-5 py-10"><section className="w-full rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
    <div className="mb-6 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 text-white"><Shield className="h-5 w-5" /></span><div><h1 className="text-xl font-black text-gray-950">Admin access</h1><p className="text-sm text-gray-500">Authorized personnel only</p></div></div>
    <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); onLogin(email, password); }}>
      <label className="block text-xs font-bold uppercase tracking-widest text-gray-500">Email<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 w-full rounded-lg border border-gray-200 px-4 py-3 text-sm normal-case tracking-normal" /></label>
      <label className="block text-xs font-bold uppercase tracking-widest text-gray-500">Password<input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-gray-200 px-4 py-3 text-sm normal-case tracking-normal" /></label>
      {error && <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm normal-case tracking-normal text-red-700">{error}</p>}
      <button disabled={busy} className="w-full rounded-lg bg-blue-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{busy ? "Signing in…" : "Sign in securely"}</button>
    </form>
  </section></main>;
}

export function AdminDashboard({ api, token, currentUser, onLogout, onUnauthorized, onForbidden }: { api: string; token: string; currentUser: AdminUser; onLogout: () => void; onUnauthorized: () => void; onForbidden: () => void }) {
  const [overview, setOverview] = useState<Overview | null>(null); const [users, setUsers] = useState<AdminUser[]>([]); const [logs, setLogs] = useState<Audit[]>([]); const [search, setSearch] = useState(""); const [roleFilter, setRoleFilter] = useState(""); const [planFilter, setPlanFilter] = useState(""); const [statusFilter, setStatusFilter] = useState(""); const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const params = new URLSearchParams({ search, role: roleFilter, plan: planFilter, status: statusFilter }); const [o, u, a] = await Promise.all([jsonRequest<Overview>(api, "/api/admin/overview", token), jsonRequest<{ users: AdminUser[] }>(api, `/api/admin/users?${params}`, token), jsonRequest<{ logs: Audit[] }>(api, "/api/admin/audit-logs?limit=50", token)]); setOverview(o); setUsers(u.users); setLogs(a.logs); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load admin data."); if (e instanceof AdminRequestError && e.status === 401) onUnauthorized(); else if (e instanceof AdminRequestError && e.status === 403) onForbidden(); } finally { setLoading(false); } }, [api, onForbidden, onUnauthorized, planFilter, roleFilter, search, statusFilter, token]);
  useEffect(() => { void load(); }, [load]);
  const mutate = async (user: AdminUser, path: string, payload: Record<string, unknown>, label: string) => { const reason = window.prompt(`Reason for ${label} on ${user.name} (${user.email}):`); if (!reason?.trim()) return; if (!window.confirm(`Confirm ${label} for ${user.name} (${user.email})?`)) return; try { await jsonRequest(api, `/api/admin/users/${user.id}/${path}`, token, { method: "PATCH", body: JSON.stringify({ ...payload, reason }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Action failed."); } };
  const changePassword = async (event: FormEvent) => { event.preventDefault(); try { await jsonRequest(api, "/api/admin/change-password", token, { method: "POST", body: JSON.stringify({ currentPassword, newPassword }) }); setCurrentPassword(""); setNewPassword(""); setError(""); window.alert("Admin password changed."); } catch (e) { setError(e instanceof Error ? e.message : "Password change failed."); } };
  const cards = overview ? [["Total users", overview.totalUsers], ["Trial Users", overview.subscription?.trialUsers || 0], ["Premium Users", overview.subscription?.premiumUsers || 0], ["Expired Users", overview.subscription?.expiredUsers || 0], ["Unlimited Users", overview.subscription?.unlimitedUsers || 0], ["Monthly Revenue", overview.subscription?.monthlyRevenue || 0], ["Sessions", overview.totalSessions], ["Caption minutes", overview.totalCaptionMinutes], ["Translation minutes", overview.totalTranslationMinutes], ["Dubbing jobs", overview.totalDubbingJobs], ["New today", overview.newUsersToday], ["New this month", overview.newUsersThisMonth]] : [];
  return <main className="mx-auto w-full max-w-7xl space-y-6 px-5 py-8">
    <div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Private administration</p><h1 className="mt-1 text-3xl font-black text-gray-950">Admin Dashboard</h1></div><button onClick={onLogout} className="inline-flex items-center gap-2 rounded-lg border border-gray-200 px-3 py-2 text-sm font-bold"><LogOut className="h-4 w-4" />Logout</button></div>
    {loading && !overview && <p className="rounded-lg border border-blue-100 bg-blue-50 p-3 text-sm text-blue-700">Loading administration…</p>}
    {error && <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <section className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-5">{cards.map(([label, value]) => <div key={label} className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-gray-500">{label}</p><p className="mt-2 text-2xl font-black text-gray-950">{Number(value).toLocaleString()}</p></div>)}</section>
    <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="mb-4 flex flex-col justify-between gap-3 lg:flex-row"><div className="flex items-center gap-2"><Users className="h-5 w-5 text-blue-600"/><h2 className="font-black">User management</h2></div><div className="flex flex-wrap gap-2"><label className="flex items-center gap-2 rounded-lg border border-gray-200 px-3"><Search className="h-4 w-4 text-gray-400"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name or email" className="py-2 text-sm outline-none"/></label><select aria-label="Filter role" value={roleFilter} onChange={(e) => setRoleFilter(e.target.value)} className="rounded-lg border border-gray-200 px-2 text-sm"><option value="">All roles</option><option value="user">User</option><option value="admin">Admin</option><option value="super_admin">Super admin</option></select><select aria-label="Filter plan" value={planFilter} onChange={(e) => setPlanFilter(e.target.value)} className="rounded-lg border border-gray-200 px-2 text-sm"><option value="">All plans</option><option value="free">Free</option><option value="pro_lite">Starter</option><option value="creator">Pro</option><option value="business">Business</option><option value="team">Team</option></select><select aria-label="Filter status" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className="rounded-lg border border-gray-200 px-2 text-sm"><option value="">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="deactivated">Deactivated</option></select></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="border-b text-xs uppercase text-gray-500"><tr><th className="p-2">User</th><th>Role</th><th>Status</th><th>Plan</th><th>Usage / sessions</th><th>Registered</th><th>Last active</th><th>Actions</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-b border-gray-100"><td className="p-2"><p className="font-bold">{user.name}</p><p className="text-xs text-gray-500">{user.email}</p></td><td>{user.role}</td><td>{user.status}</td><td>{user.planOverride || user.plan}</td><td className="text-xs">{user.usage?.dailyMinutes || 0} min today · {user.usage?.sessions || 0} sessions</td><td>{user.createdAt ? new Date(user.createdAt).toLocaleDateString() : "—"}</td><td>{user.lastActiveAt ? new Date(user.lastActiveAt).toLocaleString() : "—"}</td><td><div className="flex flex-wrap gap-1">{user.status === "active" ? <><button onClick={() => void mutate(user, "status", { status: "suspended" }, "suspension")} className="rounded bg-amber-50 px-2 py-1 text-xs text-amber-700">Suspend</button><button onClick={() => void mutate(user, "status", { status: "deactivated" }, "deactivation")} className="rounded bg-red-50 px-2 py-1 text-xs text-red-700">Deactivate</button></> : <button onClick={() => void mutate(user, "status", { status: "active" }, user.status === "deactivated" ? "account restoration" : "reactivation")} className="rounded bg-emerald-50 px-2 py-1 text-xs text-emerald-700">{user.status === "deactivated" ? "Restore" : "Reactivate"}</button>}<button onClick={() => void mutate(user, "usage", {}, "usage reset")} className="rounded bg-gray-100 px-2 py-1 text-xs">Reset usage</button><button onClick={() => void mutate(user, "plan", { planOverride: "unlimited", accessOverrideEndsAt: new Date(Date.now() + 7 * 86400000).toISOString() }, "7-day temporary access")} className="rounded bg-violet-50 px-2 py-1 text-xs text-violet-700">7d access</button><select aria-label={`Plan for ${user.email}`} value={user.planOverride || "free"} onChange={(e) => void mutate(user, "plan", { planOverride: e.target.value }, "plan change")} className="rounded border px-1 text-xs"><option value="free">Free</option><option value="starter">Starter</option><option value="pro">Pro</option><option value="unlimited">Unlimited</option></select>{currentUser.role === "super_admin" && user.role !== "super_admin" && <button onClick={() => void mutate(user, "role", { role: user.role === "admin" ? "user" : "admin" }, user.role === "admin" ? "remove admin role" : "promote to admin")} className="rounded bg-blue-50 px-2 py-1 text-xs text-blue-700">{user.role === "admin" ? "Remove admin role" : "Promote to admin"}</button>}</div></td></tr>)}</tbody></table></div>
    </section>
    <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="mb-3 font-black">Subscription management</h2><div className="overflow-x-auto"><table className="w-full min-w-[1300px] text-left text-xs"><thead><tr><th>User</th><th>Role</th><th>Plan</th><th>Status</th><th>Trial Ends</th><th>Days Remaining</th><th>Subscription</th><th>Subscription Ends</th><th>Last Payment</th><th>Provider</th><th>Actions</th></tr></thead><tbody>{users.map((user) => <tr key={`sub-${user.id}`} className="border-t"><td>{user.email}</td><td>{user.role}</td><td>{user.planLabel || user.plan}</td><td>{user.subscriptionStatus || user.status}</td><td>{user.trialEndsAt ? new Date(user.trialEndsAt).toLocaleDateString() : "Never"}</td><td>{user.daysRemaining == null ? "Never" : `${user.daysRemaining} days`}</td><td>{user.subscriptionType || "none"}</td><td>{subscriptionEndLabel(user)}</td><td>{user.lastPaymentAt ? new Date(user.lastPaymentAt).toLocaleDateString() : "—"}</td><td>{user.paymentProvider || "none"}</td><td className="space-x-1"><button onClick={() => void mutate(user, "subscription", { action: "grant_trial" }, "grant 7-day trial")}>Grant 7-day trial</button><button onClick={() => void mutate(user, "subscription", { action: "extend_trial", days: 7 }, "extend trial")}>Extend trial</button><button onClick={() => void mutate(user, "subscription", { action: "end_trial" }, "end trial now")}>End trial now</button><button onClick={() => void mutate(user, "subscription", { action: "activate", type: "monthly" }, "activate subscription")}>Activate subscription</button><button onClick={() => void mutate(user, "subscription", { action: "cancel" }, "cancel subscription")}>Cancel subscription</button><button onClick={() => void mutate(user, "subscription", { action: "unlimited" }, "convert to unlimited")}>Convert to Unlimited</button><button onClick={() => void mutate(user, "role", { role: "user" }, "convert back to user")}>Convert back to User</button><button onClick={() => void mutate(user, "subscription", { action: "expire" }, "expire immediately")}>Expire immediately</button><button onClick={() => void mutate(user, "subscription", { action: "restore" }, "restore access")}>Restore access</button></td></tr>)}</tbody></table></div></section>
    <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="mb-3 flex items-center gap-2"><Activity className="h-5 w-5 text-blue-600"/><h2 className="font-black">Recent admin activity</h2></div><div className="space-y-2">{logs.map((log) => <div key={log._id} className="flex justify-between gap-3 border-b border-gray-100 py-2 text-sm"><span><b>{log.action}</b>{log.reason ? ` — ${log.reason}` : ""}</span><time className="text-gray-500">{new Date(log.createdAt).toLocaleString()}</time></div>)}</div></section>
    <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 className="font-black">Admin account settings</h2><p className="mt-1 text-sm text-gray-500">Active session: {currentUser.email} · {currentUser.role}</p>{currentUser.mustChangePassword && <p className="mt-2 text-sm font-bold text-amber-700">Change the initial password before continuing regular administration.</p>}<form onSubmit={(event) => void changePassword(event)} className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input type="password" required value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} placeholder="Current password" className="rounded-lg border border-gray-200 px-3 py-2 text-sm"/><input type="password" minLength={10} required value={newPassword} onChange={(e) => setNewPassword(e.target.value)} placeholder="New password (10+ characters)" className="rounded-lg border border-gray-200 px-3 py-2 text-sm"/><button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white">Change password</button></form></section>
  </main>;
}
